### ISSUE TITLE
4020 blower model incorrect

### ISSUE THREAD

**Issue by gvasvari** [PrintersForAnts/Voron-Construct#10]
Hi,
The 4020 blower fan model has the same dimensions as the 5015.
The shape seems correct but simple scaling (combining uniform and non-uniform) does not solve the issue, the opening on the bottom would have other proportions - checking with the GDSTime 4020 blower GDB4020 I have at hand.

**Comment by kyleisah** [comment]
Are you able to share some screenshots with dimensions? I believe I pulled this model from afterburner but I can’t remember. I’ll take a look when I get a chance.

**Comment by gvasvari** [comment]
yep, it's from the 4020 blower step file
![image](https://github.com/PrintersForAnts/Voron-Construct/assets/7863614/ea7f9b86-29e0-4181-8b4d-13c5bd1db64c)


I found some good CAD models on Grabcad:
https://grabcad.com/library/4020-blower-fan-3
and Bigtreetech H2 CADs:
https://github.com/bigtreetech/H2-Series/blob/master/H2%20V2s%20Lite/H2%20V2S%20Lite%20w%204020%20blower%20assembly.STEP
not sure about licenses though...

**Comment by kyleisah** [comment]
Seems to be missing a whole mounting leg too. What the heck. Thanks for bringing this up, I’ll see what I can do about this.

**Comment by kyleisah** [comment]
Finally got around to this, apologize for the wait. This has been fixed. Thanks for bringing it to my attention!
